import { Poppins } from "next/font/google";

import Navbar from "@/components/Navbar/Navbar";

import "./globals.css";

const font = Poppins({
	style: ["normal", "italic"],
	weight: ["100", "300", "400", "500", "600", "700", "800"],
	subsets: ["latin", "devanagari", "latin-ext"],
});

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body className={font.className}>
				<Navbar />

				{children}
			</body>
		</html>
	);
}
